#!/usr/bin/env python3
"""Generate the minimal TypeScript SDK from the canonical OpenAPI contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


GENERATOR_NAME = "teddycloud-next-sdk-generator"
GENERATOR_VERSION = "1.0.0"
ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contracts" / "openapi.json"
OUTPUT = ROOT / "sdk" / "typescript" / "src" / "generated.ts"


def render() -> str:
    raw = CONTRACT.read_bytes()
    document = json.loads(raw)
    operation = document["paths"]["/health"]["get"]
    if document.get("openapi") != "3.1.0":
        raise ValueError("expected OpenAPI 3.1.0")
    if operation.get("operationId") != "getHealth":
        raise ValueError("expected getHealth operation")
    schema = document["components"]["schemas"]["HealthResponse"]
    if schema.get("required") != ["status", "version"]:
        raise ValueError("HealthResponse fields changed; update the generator")

    digest = hashlib.sha256(raw).hexdigest()
    return f"""// Generated by {GENERATOR_NAME} {GENERATOR_VERSION}.
// Source: contracts/openapi.json sha256:{digest}
// Do not edit manually.

export interface HealthResponse {{
  status: string;
  version: string;
}}

export interface ClientOptions {{
  baseUrl: string;
  fetchImpl?: typeof fetch;
}}

export async function getHealth(options: ClientOptions): Promise<HealthResponse> {{
  const fetchImpl = options.fetchImpl ?? fetch;
  const response = await fetchImpl(`${{options.baseUrl.replace(/\\/$/, "")}}/health`, {{
    headers: {{ accept: "application/json" }},
  }});
  if (!response.ok) {{
    throw new Error(`getHealth failed with HTTP ${{response.status}}`);
  }}
  return (await response.json()) as HealthResponse;
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()

    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(f"generated SDK is stale: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated SDK is current ({GENERATOR_NAME} {GENERATOR_VERSION})")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
