// Generated by teddycloud-next-sdk-generator 1.0.0.
// Source: contracts/openapi.json sha256:207fc69c9e3bc325016809ddbd9849e744acf648e88de6df59a7b6239d5358d1
// Do not edit manually.

export interface HealthResponse {
  status: string;
  version: string;
}

export interface ClientOptions {
  baseUrl: string;
  fetchImpl?: typeof fetch;
}

export async function getHealth(options: ClientOptions): Promise<HealthResponse> {
  const fetchImpl = options.fetchImpl ?? fetch;
  const response = await fetchImpl(`${options.baseUrl.replace(/\/$/, "")}/health`, {
    headers: { accept: "application/json" },
  });
  if (!response.ok) {
    throw new Error(`getHealth failed with HTTP ${response.status}`);
  }
  return (await response.json()) as HealthResponse;
}
